export const SPECIALTIES_LIST = [
  "Anxiety",
  "Depression",
  "Trauma & PTSD",
  "Relationships",
  "Career Counseling",
  "ADHD / Neurodivergence",
  "Grief & Loss",
  "Addiction",
  "LGBTQ+ Issues",
  "Eating Disorders",
  "Sleep Issues",
  "Parenting",
  "Stress Management",
  "Self Esteem",
  "Anger Management",
  "Bipolar Disorder",
];

export const METRO_STATIONS = [
  "Adarsh Nagar",
  "AIIMS",
  "Akshardham",
  "Anand Vihar",
  "Arjan Garh",
  "Arthala",
  "Ashok Park Main",
  "Ashram",
  "Azadpur",
  "Badarpur Border",
  "Badkal Mor",
  "Bahadurgarh City",
  "Barakhamba Road",
  "Bata Chowk",
  "Bhikaji Cama Place",
  "Botanical Garden",
  "Brigadier Hoshiyar Singh",
  "Central Secretariat",
  "Chandni Chowk",
  "Chawri Bazar",
  "Chhatarpur",
  "Chirag Delhi",
  "Civil Lines",
  "Dabri Mor - Janakpuri South",
  "Dashrath Puri",
  "Delhi Aerocity",
  "Delhi Cantonment",
  "Delhi Gate",
  "Dhansa Bus Stand",
  "Dhaula Kuan",
  "Dilli Haat - INA",
  "Dilshad Garden",
  "Durgabai Deshmukh South Campus",
  "Dwarka",
  "Dwarka Mor",
  "Dwarka Sector 8",
  "Dwarka Sector 9",
  "Dwarka Sector 10",
  "Dwarka Sector 11",
  "Dwarka Sector 12",
  "Dwarka Sector 13",
  "Dwarka Sector 14",
  "Dwarka Sector 21",
  "East Azad Nagar",
  "East Vinod Nagar - Mayur Vihar II",
  "Escorts Mujesar",
  "ESI - Basaidarapur",
  "Ghevra",
  "Ghitorni",
  "Gokulpuri",
  "Golf Course",
  "Govindpuri",
  "Greater Kailash",
  "Green Park",
  "GTB Nagar",
  "Guru Dronacharya",
  "Haiderpur Badli Mor",
  "Harkesh Nagar Okhla",
  "Hauz Khas",
  "Huda City Centre",
  "IFFCO Chowk",
  "IIT Delhi",
  "Inderlok",
  "Indira Gandhi International Airport",
  "Indraprastha",
  "IP Extension",
  "ITO",
  "Jaffrabad",
  "Jahangirpuri",
  "Jama Masjid",
  "Jamia Millia Islamia",
  "Janakpuri East",
  "Janakpuri West",
  "Jangpura",
  "Janpath",
  "Jasola Apollo",
  "Jasola Vihar Shaheen Bagh",
  "Jawaharlal Nehru Stadium",
  "Jhandewalan",
  "Jhilmil",
  "Johri Enclave",
  "Jor Bagh",
  "Kailash Colony",
  "Kalindi Kunj",
  "Kalkaji Mandir",
  "Kanhaiya Nagar",
  "Karkarduma",
  "Karkarduma Court",
  "Karol Bagh",
  "Kashmere Gate",
  "Kaushambi",
  "Keshav Puram",
  "Khan Market",
  "Kirti Nagar",
  "Krishna Nagar",
  "Krishna Park Extension",
  "Lajpat Nagar",
  "Lal Qila",
  "Laxmi Nagar",
  "Lok Kalyan Marg",
  "Madipur",
  "Maharaja Surajmal Stadium",
  "Majlis Park",
  "Major Mohit Sharma Rajendra Nagar",
  "Malviya Nagar",
  "Mandawali - West Vinod Nagar",
  "Mandi House",
  "Mansarovar Park",
  "Maujpur - Babarpur",
  "Mayapuri",
  "Mayur Vihar I",
  "Mayur Vihar Extension",
  "Mayur Vihar Pocket I",
  "Mewla Maharajpur",
  "MG Road",
  "Model Town",
  "Mohan Estate",
  "Mohan Nagar",
  "Moolchand",
  "Moti Nagar",
  "Mundka",
  "Mundka Industrial Area",
  "Munirka",
  "Najafgarh",
  "Nangli",
  "Nangloi",
  "Nangloi Railway Station",
  "Naraina Vihar",
  "Nawada",
  "Neelam Chowk Ajronda",
  "Nehru Enclave",
  "Nehru Place",
  "Netaji Subhash Place",
  "New Ashok Nagar",
  "New Delhi",
  "NHPC Chowk",
  "Nirman Vihar",
  "Noida City Centre",
  "Noida Electronic City",
  "Noida Sector 15",
  "Noida Sector 16",
  "Noida Sector 18",
  "Noida Sector 34",
  "Noida Sector 52",
  "Noida Sector 59",
  "Noida Sector 61",
  "Noida Sector 62",
  "Okhla Bird Sanctuary",
  "Okhla NSIC",
  "Okhla Vihar",
  "Old Faridabad",
  "Palam",
  "Panchsheel Park",
  "Pandit Shree Ram Sharma",
  "Paschim Vihar East",
  "Paschim Vihar West",
  "Patel Chowk",
  "Patel Nagar",
  "Peeragarhi",
  "Pitampura",
  "Pratap Nagar",
  "Preet Vihar",
  "Pul Bangash",
  "Punjabi Bagh",
  "Punjabi Bagh West",
  "Qutab Minar",
  "R. K. Puram",
  "Raja Nahar Singh",
  "Raj Bagh",
  "Rajdhani Park",
  "Rajendra Place",
  "Rajiv Chowk",
  "Rajouri Garden",
  "R. K. Ashram Marg",
  "Ramesh Nagar",
  "Rithala",
  "Rohini East",
  "Rohini Sector 18, 19",
  "Rohini West",
  "Sadar Bazaar Cantonment",
  "Saket",
  "Samaypur Badli",
  "Sant Surdas (Sihi)",
  "Sarai",
  "Sarai Kale Khan - Nizamuddin",
  "Sarita Vihar",
  "Sarojini Nagar",
  "Satguru Ram Singh Marg",
  "Sector 28",
  "Seelampur",
  "Shadipur",
  "Shahdara",
  "Shaheed Nagar",
  "Shaheed Sthal",
  "Shakurpur",
  "Shalimar Bagh",
  "Shankar Vihar",
  "Shastri Nagar",
  "Shastri Park",
  "Shiv Vihar",
  "Shivaji Park",
  "Shivaji Stadium",
  "Shyam Park",
  "Sikanderpur",
  "Sir M. Vishweshwaraiah Moti Bagh",
  "South Extension",
  "Subhash Nagar",
  "Sukhdev Vihar",
  "Sultanpur",
  "Supreme Court",
  "Tagore Garden",
  "Terminal 1-IGI Airport",
  "Tikri Border",
  "Tikri Kalan",
  "Tilak Nagar",
  "Tis Hazari",
  "Trilokpuri Sanjay Lake",
  "Tughlakabad",
  "Udyog Bhawan",
  "Udyog Nagar",
  "Uttam Nagar East",
  "Uttam Nagar West",
  "Vaishali",
  "Vasant Vihar",
  "Vidhan Sabha",
  "Vinobapuri",
  "Vishwa Vidyalaya",
  "Welcome",
  "Yamuna Bank",
  "Yashobhoomi Dwarka Sector - 25",
];
